name: autopost

on:
  schedule:
    - cron: "0 * * * *"  # 毎時
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Run generator
        run: npm run run

      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out
